version: 2.1
orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@2.2.5

jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/node:20.18
        environment:
          DB_HOST: 0.0.0.0
          DB_PORT: 5432
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_NAME: test_db
          POKEMON_API_URL: https://pokeapi.co/api/v2
          COVERALLS_REPO_TOKEN: q57b9rjKzi4VGbA1p3goR2u08ebW5syEk
      # Service container image
      - image: cimg/postgres:15.5
        environment:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test:cov
          name: Run tests with coverage
      # - run:
      #     name: Send coverage to Coveralls
      #     command: npm run coveralls
      # - run:
      #     command: npm run build
      #     name: Install and Make
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - coveralls/upload:
          path: coverage/lcov.info
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test
